/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz_app;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;

/**
 *
 * @author Master Shrijon
 */
public class choose_dialog extends java.awt.Dialog {

    /**
     * Creates new form choose_dialog
     */
    JFrame frm;
    users current_user;
    public choose_dialog(JFrame frm,users current_user) {
        super((Dialog)null);
        initComponents();
        this.frm=frm;
        this.current_user=current_user;
        this.setLocationRelativeTo(frm);
        this.setBackground(Color.WHITE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        class_box = new javax.swing.JComboBox<>();
        sub_box = new javax.swing.JComboBox<>();
        signout_button = new keeptoo.KButton();
        choose_button = new keeptoo.KButton();

        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(43, 50, 178));
        kGradientPanel1.setkStartColor(new java.awt.Color(20, 136, 204));

        class_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "class11", "class12" }));

        sub_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physics", "Chemistry", "Maths", "Biology" }));
        sub_box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        signout_button.setText("Sign Out");
        signout_button.setkBorderRadius(0);
        signout_button.setkEndColor(new java.awt.Color(179, 18, 23));
        signout_button.setkHoverEndColor(new java.awt.Color(229, 45, 39));
        signout_button.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        signout_button.setkHoverStartColor(new java.awt.Color(179, 18, 23));
        signout_button.setkStartColor(new java.awt.Color(229, 45, 39));
        signout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_buttonActionPerformed(evt);
            }
        });

        choose_button.setText("Start Quiz");
        choose_button.setkBorderRadius(0);
        choose_button.setkEndColor(new java.awt.Color(28, 117, 0));
        choose_button.setkHoverEndColor(new java.awt.Color(0, 243, 0));
        choose_button.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        choose_button.setkHoverStartColor(new java.awt.Color(28, 117, 0));
        choose_button.setkStartColor(new java.awt.Color(0, 243, 0));
        choose_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(class_box, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(sub_box, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(signout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(choose_button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class_box)
                    .addComponent(sub_box, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(choose_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(signout_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        frm.dispatchEvent(new WindowEvent(frm,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeDialog

    private void signout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        frm.setVisible(true);
    }//GEN-LAST:event_signout_buttonActionPerformed

    private void choose_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_buttonActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        this.setVisible(false);
        dispose();
        new question_dialog(frm,current_user,(String)class_box.getSelectedItem(),(String)sub_box.getSelectedItem());
    }//GEN-LAST:event_choose_buttonActionPerformed

    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton choose_button;
    private javax.swing.JComboBox<String> class_box;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KButton signout_button;
    private javax.swing.JComboBox<String> sub_box;
    // End of variables declaration//GEN-END:variables
}
