/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz_app;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.WindowEvent;
import java.io.*;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import mdlaf.utils.MaterialColors;

/**
 *
 * @author Master Shrijon
 */
public class question_dialog extends java.awt.Dialog
{

    /**
     * Creates new form question_dialog
     */
    question current, start;
    JFrame frm;
    int result;
    users current_user;
    String clas,sub;

    public question_dialog(JFrame frm,users current_user,String clas,String sub)
    {
        super((Dialog)null);
        initComponents();
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        result = 0;
        this.frm = frm;
        this.clas=clas;
        this.sub=sub;
        this.current_user=current_user;
        this.setLocationRelativeTo(frm);
        this.setBackground(MaterialColors.WHITE);
        this.setVisible(true);
        try
        {
            //System.out.println("C:/Users/Master Shrijon/Documents/NetBeansProjects/Quiz_app/src/quiz_app/"+clas+sub);
            BufferedReader br = new BufferedReader(new FileReader(clas+sub+".txt"));
            start = current = new question(null, br);
            question_area.setText(current.q);
            op1.setText(current.op1);
            op2.setText(current.op2);
            op3.setText(current.op3);
            op4.setText(current.op4);
        } catch (Exception e)
        {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        question_area = new javax.swing.JTextArea();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        prev_button = new keeptoo.KButton();
        nxt_button = new keeptoo.KButton();

        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        buttonGroup.add(op1);
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setText("<html>op1</html>");
        op1.setOpaque(false);
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_actionPerformed(evt);
            }
        });

        buttonGroup.add(op2);
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setText("<html>op2</html>");
        op2.setOpaque(false);
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_actionPerformed(evt);
            }
        });

        buttonGroup.add(op3);
        op3.setForeground(new java.awt.Color(255, 255, 255));
        op3.setText("<html>op3</html>");
        op3.setOpaque(false);
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_actionPerformed(evt);
            }
        });

        buttonGroup.add(op4);
        op4.setForeground(new java.awt.Color(255, 255, 255));
        op4.setText("<html>op4</html>");
        op4.setOpaque(false);
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_actionPerformed(evt);
            }
        });

        jScrollPane2.setOpaque(false);
        jScrollPane2.setViewportView(null);

        question_area.setEditable(false);
        question_area.setColumns(20);
        question_area.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        question_area.setForeground(new java.awt.Color(255, 255, 255));
        question_area.setLineWrap(true);
        question_area.setRows(5);
        question_area.setText("question_area");
        question_area.setWrapStyleWord(true);
        question_area.setOpaque(false);
        jScrollPane2.setViewportView(question_area);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(43, 50, 178));
        kGradientPanel1.setkStartColor(new java.awt.Color(20, 136, 204));

        prev_button.setText("Prev");
        prev_button.setkBorderRadius(0);
        prev_button.setkHoverEndColor(new java.awt.Color(0, 102, 102));
        prev_button.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        prev_button.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        prev_button.setkStartColor(new java.awt.Color(0, 102, 102));
        prev_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt_prev_buttonActionPerformed(evt);
            }
        });

        nxt_button.setForeground(new java.awt.Color(0, 0, 0));
        nxt_button.setText("Next");
        nxt_button.setkBorderRadius(0);
        nxt_button.setkEndColor(new java.awt.Color(51, 0, 27));
        nxt_button.setkHoverEndColor(new java.awt.Color(255, 0, 132));
        nxt_button.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        nxt_button.setkHoverStartColor(new java.awt.Color(51, 0, 27));
        nxt_button.setkStartColor(new java.awt.Color(255, 0, 132));
        nxt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt_prev_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(prev_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(nxt_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nxt_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prev_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op4, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(op1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(op3))
                        .addGap(37, 37, 37))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        frm.dispatchEvent(new WindowEvent(frm, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeDialog

    private void nxt_prev_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt_prev_buttonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == nxt_button)
        {
            if (nxt_button.getText() == "Submit")
            {
                this.setVisible(false);
                dispose();
                new result_dialog(frm,current_user).show_res(start);
            }
            if (current.nxt == null)
            {
                nxt_button.setText("Submit");
                return;
            }
            prev_button.setEnabled(true);
            current = current.nxt;

        } else
        {
            if (current.prev == null)
            {
                prev_button.setEnabled(false);
                return;
            }
            nxt_button.setText("next");
            current = current.prev;
        }
        question_area.setText(current.q);
        op1.setText(current.op1);
        op2.setText(current.op2);
        op3.setText(current.op3);
        op4.setText(current.op4);
        if (current.choice.equals(""))
        buttonGroup.clearSelection();
        else
        {
            JRadioButton b = null;
            if (op1.getText().equals(current.choice))
            {
                b = op1;
            } else if (op2.getText().equals(current.choice))
            {
                b = op2;
            } else if (op3.getText().equals(current.choice))
            {
                b = op3;
            } else if (op4.getText().equals(current.choice))
            {
                b = op4;
            }
            b.setSelected(true);
        }
    }//GEN-LAST:event_nxt_prev_buttonActionPerformed

    private void options_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_actionPerformed
        // TODO add your handling code here:

        if (((JRadioButton) evt.getSource()).getText().equals(current.ans))
        {
            current.choice = ((JRadioButton) evt.getSource()).getText();
        } else
        {
            current.choice = ((JRadioButton) evt.getSource()).getText();
        }
    }//GEN-LAST:event_options_actionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KButton nxt_button;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private keeptoo.KButton prev_button;
    private javax.swing.JTextArea question_area;
    // End of variables declaration//GEN-END:variables
}
